### ISSUE TITLE
Grafico piatto - Script time series 1.R Compattato

### ISSUE THREAD

**Issue by FreeEagle76** [r-lab-milano/r-lab3-shinyMilano#4]
Avviando lo script modificato ottengo un grafico piatto. Controllando il dataset, derivato dai calcoli dello script, la colonna "IMPORTO" ha lo stesso valore.

Andando a ritroso sulle righe del codice, sembrerebbe che alla riga 31 l'istuzione `mutate(Total = sum(IMPORTO)` faccia la somma dei valori contenuti nella colonna "IMPORTO" e la riporta su tutta la colonna.

**Comment by siscia** [comment]
Mi pare abbiamo risolto il problema su slack. Marco come chiuso, nel caso riapriamo pure l issues.
